name: Docker Image CI

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Docker image
      run: |
        echo ${{ github.workflow }}
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo ${{ steps.vars.outputs.sha_short }}
        echo ${GITHUB_SHA::8}
        docker build . --file build/Dockerfile --tag ghcr.io/pmaishev/dls2023-pm-final-project_tb/${{ github.ref_name }}:${{ steps.vars.outputs.sha_short }}
        docker push ghcr.io/pmaishev/dls2023-pm-final-project_tb/${{ github.ref_name }}:${{ steps.vars.outputs.sha_short }}
