name: Docker Image CI

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push the Docker image
      run: |
        echo ${{ github.workflow }}
        echo "SHORT_SHA=`echo ${{ github.sha::7 }} | cut -c1-8`" >> $GITHUB_ENV
        echo ${SHORT_SHA}
        docker build . --file build/Dockerfile --tag ghcr.io/pmaishev/dls2023-pm-final-project_tb/${{ github.ref_name }}:${SHORT_SHA}
        docker push ghcr.io/pmaishev/dls2023-pm-final-project_tb/${{ github.ref_name }}:${SHORT_SHA}
